version: '3'

services:
  api:
    image: node:14.16.1-alpine3.11
    depends_on:
      - db
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
    ports:
      - ${API_PORT}:${API_PORT}
    working_dir: '/app'
    command: npm run dev

  db:
    image: postgres:13.0-alpine
    environment:
      PGPORT: ${PGPORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${PGPORT}:${PGPORT}

  prisma-studio:
    image: node:14.16.1-alpine3.11
    depends_on:
      - api
    working_dir: '/app'
    volumes:
      - ./:/app
    ports:
      - 5555:5555
    command: npm run prisma:studio

volumes:
  db-data:
