version: '3'

services:
  api:
    image: 080953414563.dkr.ecr.eu-west-3.amazonaws.com/unotifier:latest
    environment:
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    environment:
      PGPORT: ${PGPORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
